; (Unofficial) Gentoo Package Management Standard ABNF: EAPI
; Copyright (C) 2013  Walter Stanish
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
;
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <http://www.gnu.org/licenses/>.

; structural view
eapi-name             = eapi-name-first-char 0*eapi-name-char
eapi-name-first-char  = capital-letter / lowercase-letter / digit / underscore
eapi-name-char        = eapi-name-first-char / hyphen / dot / plus

; ontological view
eapi-name-categories  = eapi-cat-numeric / eapi-cat-special
eapi-cat-numeric      = eapi-cat-issued / eapi-cat-reserved
eapi-cat-issued       = eapi-0 / eapi-1 / eapi-2 / eapi-3 / eapi-4 / eapi-5
eapi-cat-reserved     = eapi-6 / eapi-7 / eapi-8 / eapi-9
eapi-cat-special      = eapi-cat-paludis-eapi
eapi-cat-paludis-eapi = "paludis-" 0*eapi-name-char
eapi-0                = "0"
eapi-1                = "1"
eapi-2                = "2"
eapi-3                = "3"
eapi-4                = "4"
eapi-5                = "5"
eapi-6                = "6"
eapi-7                = "7"
eapi-8                = "8"
eapi-9                = "9"

; general entities
capital-letter       = "A" / "B" / "C" / "D" / "E" / "F" / "G" / "H" / "I" / "J" / "K" / "L" / "M" / "N" / "O" / "P" / "Q" / "R" / "S" / "T" / "U" / "V" / "W" / "X" / "Y" / "Z"
lowercase-letter     = "a" / "b" / "c" / "d" / "e" / "f" / "g" / "h" / "i" / "j" / "k" / "l" / "m" / "n" / "o" / "p" / "q" / "r" / "s" / "t" / "u" / "v" / "w" / "x" / "y" / "z"
digit                = "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
underscore           = "_"
hyphen               = "-"
dot                  = "."
plus                 = "+"
